[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"
[project]
name = "reactor_mindstormpro3"
version = "1.0.0"
authors = [
  { name="Elio A.", email="elioanon20@Proton.me" },
]
description = "A local runner for bots built for https://defector.hackclub.com"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "requests",
    "shutils",
    "BeautifulSoup4",
    "textual",
    "py_mini_racer"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/pypa/sampleproject"
Issues = "https://github.com/pypa/sampleproject/issues"
[project.scripts]
reactor = "reactor_mindstormpro3.main:run"