from enum import Flag
import random
from py_mini_racer import MiniRacer
import os, os.path
import re
import json
import itertools
import requests
import time
import shutil

from bs4 import BeautifulSoup

from textual import work
from textual.app import App, ComposeResult
from textual.containers import VerticalScroll, HorizontalGroup, Center
from textual.widgets import Footer, Header, Button, DataTable


numOfBots = len([name for name in os.listdir('.') if os.path.isfile(name)])

botFiles = []

botList = []
bots = {}

leaderboardData = []

# generated by Claude :(, it's just a filler script to fix the fact that .at doesnt exist in the latest version of mini-racer for arrays :(
polyfillScript = """ 
if (!Array.prototype.at) {
    Array.prototype.at = function(index) {
        index = Math.trunc(index) || 0;
        if (index < 0) index += this.length;
        if (index < 0 || index >= this.length) return undefined;
        return this[index];
    };
}

"""


callScript = """
globalThis.botFuncCaller = function(jsonText) {
    const [history, memory] = JSON.parse(jsonText);
    const result = globalThis.botFunc({ history, memory });
    return JSON.stringify(result);
}
"""



class ReactorRunner(HorizontalGroup):
    def devalue_resolve(self, index, pool, cache=None): # AI WROTE THIS FUNCTION
        if cache is None:
            cache = {}
        if index in cache:
            return cache[index]

        value = pool[index]

        # Strings, numbers, booleans, None are already "final" -- no further lookup needed
        if isinstance(value, (str, int, float, bool)) or value is None:
            cache[index] = value
            return value

        # A dict's values are indices pointing elsewhere -- resolve each one
        if isinstance(value, dict):
            resolved = {}
            cache[index] = resolved
            for key, ref in value.items():
                resolved[key] = self.devalue_resolve(ref, pool, cache) if isinstance(ref, int) else ref
            return resolved

        if isinstance(value, list):
            # A list starting with a known type name is a "tagged" special value
            if len(value) > 0 and isinstance(value[0], str) and value[0] in ("Date", "Map", "Set", "RegExp", "BigInt"):
                if value[0] == "Date":
                    cache[index] = value[1]  # just keep the ISO date string
                    return value[1]
                cache[index] = value  # fallback: leave other rare tags as-is
                return value

            # Otherwise, it's a plain array of index references
            resolved = []
            cache[index] = resolved
            for ref in value:
                resolved.append(self.devalue_resolve(ref, pool, cache) if isinstance(ref, int) else ref)
            return resolved

        cache[index] = value
        return value

    @work(thread=True)
    def refreshCache(self):
        
        global botFiles, botList, bots, leaderboardData, numOfBots
        try:
            response = requests.get(
                "https://defector.hackclub.com/_app/remote/1jsclqx/leaderboardData", timeout=10, stream=True
            )
            response.raise_for_status()
        except Exception as e:
            self.log(f"Leaderboard request failed :( error: {e}")
            return  
        pool = None
        for raw_line in response.iter_lines(decode_unicode=True):
            if raw_line and raw_line.startswith("data: "):
                payload = raw_line[len("data: "):]
                parsed = json.loads(payload)
                pool = json.loads(parsed["result"])
                response.close()
                break
        response.raise_for_status()
        topBots = self.devalue_resolve(0, pool)["bots"]
        shutil.rmtree(os.path.join(os.getcwd(), "cachedBots/"))
        os.mkdir(os.path.join(os.getcwd(), "cachedBots/"))
        for bot in topBots:
            self.log(f"Fetching {bot['name']}...")
            response = requests.get(f"https://defector.hackclub.com/bot/{bot["id"]}")
            response.raise_for_status()
            source = BeautifulSoup(response.text, "html.parser").find_all("pre")[-1].get_text()
            filepath = os.path.join("cachedBots/", re.sub(r'[^a-zA-Z0-9_-]', '', bot["name"]) + ".js")
            with open(filepath, 'w', encoding="utf-8") as f:
                f.write(source)
                time.sleep(0.1)
            numOfBots = len([name for name in os.listdir('.') if os.path.isfile(name)])
            botFiles = []
            botList = []
            bots = {}
            leaderboardData = []
        for root, _, files in os.walk(os.getcwd() + "\\cachedBots\\"): 
            for filename in files:  # loop through files in the current directory
                botFiles.append(os.path.join(root, filename))
                botList.append(filename)
                print(filename)
                with open(os.path.join(root, filename), "r") as f:
                    bots[filename] = {}
                    bots[filename]["name"] = re.sub(r'[^a-zA-Z0-9_-]', '', os.path.splitext(filename)[0]) 
                    bots[filename]["code"] = polyfillScript + f.read().replace("export default", "globalThis.botFunc =") + callScript
                    ctx = MiniRacer()
                    ctx.eval(bots[filename]["code"])
                    bots[filename]["ctx"] = ctx
        self.query_one("#run").disabled = False
        self.query_one("#select").disabled = False


            
    def updateLeaderboard(self, history, bot1, bot2, err):
        table = self.parent.query_one("#leaderboard", DataTable)
        #calculate avgs?
        bots[bot1]["avg"] = bots[bot1]["score"] / bots[bot1]["played"]
        bots[bot2]["avg"] = bots[bot2]["score"] / bots[bot2]["played"]
        def sortLeaderboard(e):
            if bots[e].get("avg") is None:
                bots[e]["avg"] = "Avg Err"
                return "0"
            return str(bots[e].get("avg"))
        leaderboardData.sort(reverse=True, key=sortLeaderboard)
        table.clear()
        table.zebra_stripes = True
        for i in range(0, len(leaderboardData)):
            if bots[leaderboardData[i]]["wins"] == 0:
                bots[leaderboardData[i]]["winRate"] = 0
            else:
                bots[leaderboardData[i]]["winRate"] = bots[leaderboardData[i]]["games"] / bots[leaderboardData[i]]["wins"]
            table.add_row(leaderboardData[i], bots[leaderboardData[i]]["avg"], bots[leaderboardData[i]]["games"], bots[leaderboardData[i]]["wins"], bots[leaderboardData[i]]["losses"])

    #@work(thread=True)
    def playRounds(self, numOfRounds, bot1, bot2):
        bot1memory = None
        bot1history = []
        bot1move = None
        bot1score: int = 0
        bot2memory = None
        bot2history = []
        bot2move = None
        bot2score: int = 0
        history = []
        for i in range(1, numOfRounds + 1):
            try:

                bot1output = json.loads(bots[bot1]["ctx"].call("botFuncCaller", json.dumps([bot1history, bot1memory])))
                bot1move = bot1output[0]
                bot1memory = bot1output[1]
                if not (bot1move.lower() == "d" or bot1move.lower() == "c"):
                    print(f"oopsie it appears that {bot1} made an illegal move against {bot2}! :b")
                    return None, bot1, bot2, True
            except Exception as e:
                print(f"{bot1} crashed against {bot2}: {e}")
                return None, bot1, bot2, True
            try:

                bot2output = json.loads(bots[bot2]["ctx"].call("botFuncCaller", json.dumps([bot2history, bot2memory])))
                bot2move = bot2output[0]
                bot2memory = bot2output[1]
                if not (bot2move.lower() == "d" or bot2move.lower() == "c"):
                    print(f"oopsie it appears that {bot2} made an illegal move against {bot1}! :b")
                    return None, bot1, bot2, True
            except Exception as e:
                print(f"{bot1} crashed against {bot2}: {e}")
                return None, bot1, bot2, True

            bot1history.append({"you": bot1move, "opponent": bot2move})
            bot2history.append({"you": bot2move, "opponent": bot1move})
            history.append([bot1move, bot2move])
            if bot1move.lower() == "c" and bot2move.lower() == "c":
                bot1score = bot1score + 2
                bot2score = bot2score + 2
            if bot1move.lower() == "d" and bot2move.lower() == "c":
                bot1score = bot1score + 3
            if bot1move.lower() == "c" and bot2move.lower() == "d":
                bot2score = bot2score + 3
            if bot1move.lower() == "d" and bot2move.lower() == "d":
                bot1score = bot1score + 1
                bot2score = bot2score + 1
        
        ctx = MiniRacer()
        ctx.eval(bots[bot1]["code"])
        bots[bot1]["ctx"] = ctx
        if bots[bot1].get("score") is None:
            bots[bot1]["score"] = bot1score
            bots[bot1]["played"] = numOfRounds
            bots[bot1]["games"] = 1
            bots[bot1]["wins"] = 0
            bots[bot1]["losses"] = 0
            leaderboardData.append(bot1)
        else:
            bots[bot1]["games"] = bots[bot1]["games"] + 1
            bots[bot1]["score"] = bots[bot1]["score"]  + bot1score
            bots[bot1]["played"] = numOfRounds + bots[bot1]["played"]
        ctx = MiniRacer()
        ctx.eval(bots[bot2]["code"])
        bots[bot2]["ctx"] = ctx
        if bots[bot2].get("score") is None:
            bots[bot2]["score"] = bot2score
            bots[bot2]["played"] = numOfRounds
            bots[bot2]["games"] = 1
            bots[bot2]["wins"] = 0
            bots[bot2]["losses"] = 0
            leaderboardData.append(bot2)
        else:
            bots[bot2]["games"] = bots[bot2]["games"] + 1
            bots[bot2]["score"] = bots[bot2]["score"]  + bot2score
            bots[bot2]["played"] = numOfRounds + bots[bot2]["played"]

        if bot1score > bot2score:
            bots[bot1]["wins"] += 1
            bots[bot2]["losses"] +=1
        else:
            bots[bot2]["wins"] += 1
            bots[bot1]["losses"] +=1
        self.app.call_from_thread(self.updateLeaderboard, history, bot1, bot2, False)
        
    @work(thread=True)
    def runSim(self):
        
        for bot1, bot2 in itertools.combinations(botList, 2):
            for i in range(1, 4):
                self.playRounds(random.randrange(100, 150, 1), bot1, bot2)

    def on_button_pressed(self, event: Button.Pressed) -> None:
        if event.button.id == "run":
            self.runSim()
        elif event.button.id == "refresh":
            self.refreshCache()
            self.query_one("#run").disabled = True
            self.query_one("#select").disabled = True
        elif event.button.id == "select":
            self.selectBot()
            self.add_class("selecting")
        elif event.button.id == "cancel":
            self.remove_class("selecting")

    def compose(self) -> ComposeResult:
        yield Button("Run Reactor", id="run", variant="success")
        yield Button("Select A Bot", id="select", variant="success")
        yield Button("Cancel", id="cancel", variant="error")
        yield Button("Refresh Bot Cache", id="refresh", variant = "warning")

class ReactorApp(App):
    CSS_PATH = "reactorApp.tcss"
    BINDINGS: list[tuple[str, str, str]] = []

    def compose(self) -> ComposeResult:
        """Create child widgets for the app."""
        yield Header()
        yield Footer()
        yield ReactorRunner()
        yield DataTable(id="leaderboard")

    def on_mount(self):
        table = self.query_one("#leaderboard", DataTable)
        table.clear()
        table.zebra_stripes = True
        table.add_columns("Bot Name", "Avg Score", "Games Played", "Wins", "Losses")



if __name__ == "__main__":
    os.makedirs("cachedBots", exist_ok=True)

    for root, _, files in os.walk(os.getcwd() + "\\cachedBots\\"):  
        for filename in files:  # loop through files in the current directory
            botFiles.append(os.path.join(root, filename))
            botList.append(filename)
            print(filename)
            with open(os.path.join(root, filename), "r") as f:
                bots[filename] = {}
                bots[filename]["name"] = re.sub(r'[^a-zA-Z0-9_-]', '', os.path.splitext(filename)[0]) 
                bots[filename]["code"] = polyfillScript + f.read().replace("export default", "globalThis.botFunc =") + callScript
                ctx = MiniRacer()
                ctx.eval(bots[filename]["code"])
                bots[filename]["ctx"] = ctx
    app = ReactorApp()
    app.run()